name: multibench
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- 只固定最核心的Python和PyTorch ---
  - python=3.8.5
  - pytorch=1.8.1
  - torchvision=0.9.1

  # --- 其他重要库不再指定版本，让求解器自动寻找兼容的版本 ---
  - scikit-learn
  - pandas
  - numpy

  # --- 其他项目需要的工具包 ---
  - matplotlib
  - h5py
  - jupyter
  - gensim
  - nltk
  - seaborn
  - flask
  - beautifulsoup4
  - pillow
  - imageio
  - statsmodels
  - theano
  - pmdarima
  - memory-profiler

  # --- Pip包 ---
  - pip
  - pip:
    - fannypack
    - simple-term-menu